### ISSUE TITLE
TypeError: 'type' object is not subscriptable on 0.7.0 with python3.7

### ISSUE THREAD

**Issue by Kobidav** [lucasheld/uptime-kuma-api#13]
Hello. 
uptime-kuma-api==0.7.0 if failing with python3.7 with this error:
```
from uptime_kuma_api import UptimeKumaApi, MonitorType
  File "/home/user/.local/lib/python3.7/site-packages/uptime_kuma_api/__init__.py", line 11, in <module>
    from .api import UptimeKumaApi
  File "/home/user/.local/lib/python3.7/site-packages/uptime_kuma_api/api.py", line 188, in <module>
    timeRange: list[dict] = None
TypeError: 'type' object is not subscriptable
```

0.6.0 version is working fine with python3.7
Both version are working fine with Python3.9.6.

**Comment by lucasheld** [comment]
Thank you for reporting this problem.
I have removed unsupported type hints on old python versions in uptime-kuma-api version [0.7.1](https://github.com/lucasheld/uptime-kuma-api/releases/tag/0.7.1).

From now on I'm also using python 3.6 in my dev environment.
