### ISSUE TITLE
Get all Monitors Status

### ISSUE THREAD

**Issue by mariogarridopt** [lucasheld/uptime-kuma-api#15]
Question:

I need to check if a monitor is Up or Down.
`api.get_monitors()` gives me the monitor info, but how can I check if the monitor is up or down at this moment?

**Comment by mariogarridopt** [comment]
Is this the only way?
```python
from uptime_kuma_api import UptimeKumaApi, MonitorType

# connect
api = UptimeKumaApi('http://localhost:3001')
api.login('admin', 'admin')

monitor_list = api.get_monitors() # get all monitors
for monitor in monitor_list:
    beats = api.get_monitor_beats(monitor['id'],24) # check 24h beats
    print(beats[-1]['status'])

api.disconnect()
```

**Comment by lucasheld** [comment]
That's the only way I know.

In this case, it is sufficient to request the last hour:
```python
api.get_monitor_beats(monitor['id'], 1)
```

**Comment by lucasheld** [comment]
Yes, of course that's true. The period must be greater than the monitor check interval. Sorry for the confusion.

I just checked how Uptime Kuma indicates on the dashboard when a monitor is down. They request the heartbeat list and extract the last heartbeat for each monitor.
- https://github.com/louislam/uptime-kuma/blob/54d4c4d3f76934e4392e209b58eb2d081ee36293/src/mixins/socket.js#L611-L614
- https://github.com/louislam/uptime-kuma/blob/54d4c4d3f76934e4392e209b58eb2d081ee36293/src/components/Uptime.vue#L47-L49

Then you don't have to worry about what period is needed when requesting the monitor beats.

Example:
```python
heartbeats = api.get_important_heartbeats()
for heartbeat in heartbeats:
    monitor_id = heartbeat["id"]
    status = heartbeat["data"][-1]["status"]
    print(status)
```

Here I used important heartbeats, I think they are enough for this.

**Comment by mariogarridopt** [comment]
Yes, this is a cool way to go about it.
Thanks for the research on uptime-kuma. 

Still, I think it would be useful to have an `is_up(monitor_id)` or something.

> Then you don't have to worry about what period is needed when requesting the monitor beats.

Right but we solve one problem at a cost of another because now I have to match that data with the total monitors I have to understand what's up or down.

But I get your point: We have ways to get this information today.

**Comment by pixelrazor** [comment]
To go further on this: How do we check the status of a monitor to include maintenance? [this](https://github.com/louislam/uptime-kuma/blob/54d4c4d3f76934e4392e209b58eb2d081ee36293/src/components/Uptime.vue#L47-L49) suggests at least 4 possible states. The heartbeat shows up or down. Do i need to derive the proper status from a combination of heartbeat status and the `maintenance` field in GetMonitor(s)?

**Comment by lucasheld** [comment]
@pixelrazor You are right, this is currently not possible: https://github.com/lucasheld/uptime-kuma-api/issues/30

**Comment by lucasheld** [comment]
I think I will add a method `get_monitor_status(monitor_id: int)` that returns the current status (`DOWN`, `UP`, `PENDING`, `MAINTENANCE`) of the monitor with that id.
