### ISSUE TITLE
Assign tags to monitor

### ISSUE THREAD

**Issue by kj187** [lucasheld/uptime-kuma-api#17]
First of all, nice work! Thanks! 
But currently it is not possible to assign tags to a monitor or is it possible? 
Cant find any tag key in the monitor schema API for that ;(

**Comment by mariogarridopt** [comment]
I was looking in the docs: https://uptime-kuma-api.readthedocs.io/en/latest/

Looks like you can using:
```python
api.add_monitor_tag(
    tag_id=1,
    monitor_id=1,
    value="test"
)
```

**Comment by kj187** [comment]
Works! Thanks!
