### ISSUE TITLE
Support login / use via api-key

### ISSUE THREAD

**Issue by simonmicro** [lucasheld/uptime-kuma-api#24]
Hi,
I wanted to use this wonderful project for some hobby-stuff, but it turns out that the `login()` method does not support the "api-key" authentication method. In combination with enabled 2FA it is somewhat hard to use this project... Would it be possible to add support for that? Maybe I'm just too stupid to read the documentation properly :wink: 
~Simon

...and I also tried `login_by_token()`, which just times out / reports invalid api keys.

**Comment by Vinalti** [comment]
Did you try with using a normal login with empty username `""` and the api_key as password? I didn't try but that worked in the browser.

**Comment by Vinalti** [comment]
It seems to be native from UptimeKuma SocketIO endpoint, so I raised an issue there: https://github.com/louislam/uptime-kuma/issues/3107

**Comment by simonmicro** [comment]
> I could reproduce the issue, I cannot connect to kuma with the API token... sweat_smile

I've also tried that, after reading in the documentation how the basic authentication should work. Didn't work :grimacing:

**Comment by Vinalti** [comment]
See #28

**Comment by simonmicro** [comment]
Well, this answers my question - let's hope they add proper token support via https://github.com/louislam/uptime-kuma/issues/3107 .

_On the other hand, they mention token support for the http-api in their documentation..._

**Comment by lucasheld** [comment]
So this issue can be closed then?

**Comment by simonmicro** [comment]
Fair point, this repo shall not have issues open, which are an issue in the upstream project!

Anybody else coming here - keep an eye onto https://github.com/louislam/uptime-kuma/issues/3107!
