### ISSUE TITLE
Use Uptime Kuma API key for authentication

### ISSUE THREAD

**Issue by FliKites** [lucasheld/uptime-kuma-api#39]
Currently, I have to resort to exposing plaintext login credentials to use this API - it would be cool to use an API key generated in Uptime Kuma to be able to authenticate.

Please let me know if this would be possible. Thanks.

**Comment by GoingtohellYT** [comment]
I totally agree. Moreover login in using the current method is a real pain for those who have 2fa enabled. Using the API key would in my opinion show a fgew benefits

**Comment by lucasheld** [comment]
It has already been mentioned here: https://github.com/lucasheld/uptime-kuma-api/issues/24
Unfortunately, it is currently not possible to use API Keys in combination with the Socket.IO API endpoint. API Keys can only be used to access the Prometheus metrics endpoint. This has nothing to do with activated 2FA.
