### ISSUE TITLE
Missing sanitisation of `accepted_statuscodes`

### ISSUE THREAD

**Issue by CommanderStorm** [lucasheld/uptime-kuma-api#42]
Hello,

Given that your release cycles are probably better than ours, could you add a check for this issue in the api-wrapper?  https://github.com/louislam/uptime-kuma/issues/3520
We will also get on providing a fix upstream, as this would be a security issue if we had multi-user implemented.

Greetings Frank

**Comment by lucasheld** [comment]
Thank you for creating this issue.
