### ISSUE TITLE
Interval modification does not take effect

### ISSUE THREAD

**Issue by bogeit** [lucasheld/uptime-kuma-api#43]
The display of the return result of the call looks normal, but the modification cannot actually be successful.

>>> api.edit_monitor(2,Interval=30)
{'msg': 'Saved.', 'monitorID': 2}

**Comment by lucasheld** [comment]
The parameter needs to be lower case `interval` as described in [the docs](https://uptime-kuma-api.readthedocs.io/en/latest/api.html#uptime_kuma_api.UptimeKumaApi.edit_monitor).

But the module should not send the request to uptime kuma if an unknown parameter is specified. I will implement that.

**Comment by bogeit** [comment]
> The parameter needs to be lower case `interval` as described in [the docs](https://uptime-kuma-api.readthedocs.io/en/latest/api.html#uptime_kuma_api.UptimeKumaApi.edit_monitor).
> 
> But the module should not send the request to uptime kuma if an unknown parameter is specified. I will implement that.

thanks.
