### ISSUE TITLE
need to modify the value of interval and retryInterval to make it lower than 20

### ISSUE THREAD

**Issue by bogeit** [lucasheld/uptime-kuma-api#47]
Sometimes I need to modify the value of interval and retryInterval to make it lower than 20. I have modified the uptime-kuma related code files and repackaged the docker image, but there is a limit on the api here. I don’t know if this limit can No looser, in order to meet this modification requirements
https://github.com/lucasheld/uptime-kuma-api/blob/master/uptime_kuma_api/api.py#L287

>>> api.edit_monitor(1, interval=5)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 1332, in edit_monitor
     return self._call('editMonitor', data)
   File "/usr/local/lib/python3.10/dist-packages/uptime_kuma_api/api.py", line 506, in _call
     raise UptimeKumaException(r. get("msg"))
uptime_kuma_api.exceptions.UptimeKumaException: Interval cannot be less than 20 seconds

**Comment by lucasheld** [comment]
I think then you also have to adjust the code of this python module. The condition prevents sending invalid values to uptime Kuma.

**Comment by bogeit** [comment]
> I think then you also have to adjust the code of this python module. The condition prevents sending invalid values to uptime Kuma.

ok, I know, thanks.
