### ISSUE TITLE
support uptime kuma v1.23.0

### ISSUE THREAD

**Issue by obfusk** [lucasheld/uptime-kuma-api#49]
This has several new features (like JSON query monitors): https://github.com/louislam/uptime-kuma/releases/tag/1.23.0

Happy to help figure out what needs changing to support the changes :)

See also #48.

**Comment by lucasheld** [comment]
To do this I need to compare all the changes to the source code between the tags 1.22.1 and 1.23.0 and also analyze the requests and responses between Uptime Kuma and the web browser. There are a lot of changes. I have already started implementing them, but I need more time.

**Comment by obfusk** [comment]
> There are a lot of changes. I have already started implementing them, but I need more time.

Of course. And thank you. FWIW I briefly looked at all the source code changes for anything that looked like it would break existing uses. The only thing that seemed like a breaking change was #48, which seems to be fixed with that patch. And possibly the change for `gamedig` (which we don't use ourselves). The rest mostly seemed like new additions that need support but would not break existing deployments using existing features. So far ours seems to work fine with that single patch.

**Comment by lucasheld** [comment]
Uptime Kuma 1.23.1 is supported in version 1.2.0.
