### ISSUE TITLE
Default info event does not fetch version under uptime-kuma with version 1.23.1

### ISSUE THREAD

**Issue by iTerminate** [lucasheld/uptime-kuma-api#55]
Intermittent issue. API calls fail due to lack of version. 

Sample output for uptime-kuma-api.info()
```
{'primaryBaseURL': None, 'serverTimezone': 'America/Chicago', 'serverTimezoneOffset': '-05:00'}
```

See https://github.com/louislam/uptime-kuma/commit/be26bb75d9a54debad31a3914bbf072bc929cc7c

**Comment by lucasheld** [comment]
This bug only occurred if the `wait_events` setting was set too low. If `wait_events` was high enough, the second info event was used automatically. This is fixed now.
But everyone who had this problem should set `wait_events` higher to avoid problems in other places.
