### ISSUE TITLE
save_status_page() failing because of unexpected keyword.

### ISSUE THREAD

**Issue by b-trendafilov** [lucasheld/uptime-kuma-api#58]
doing the following api call:

```
   api.save_status_page(
        slug="test",
        title="test Title",
        description="This is a test",
        publicGroupList=[
            {
                'name': 'Test',
                'weight': 1,
                'monitorList': [
                    {
                        "id": 33
                    }
                ]
            }
        ]
    )
```

but I get the following result:
TypeError: UptimeKumaApi._build_status_page_data() got an unexpected keyword argument 'showCertificateExpiry'

**Comment by obfusk** [comment]
Are you using a version of uptime-kuma-api less than 1.2.0 with uptime kuma 1.23.0 or later?

**Comment by obfusk** [comment]
Because in that case you need at least 1.2.0, which added support for uptime kuma 1.23.0 and 1.23.1.

**Comment by b-trendafilov** [comment]
walk of shame....

Thanks for the help, closing the issue
