### ISSUE TITLE
How do I add monitors to status pages?

### ISSUE THREAD

**Issue by AMDTonyRyzen** [lucasheld/uptime-kuma-api#8]
Hi, can you tell me how I can change the status_page data using the python api. Apparently, the following function <sup>save_status_page(self, slug: str, **kwargs)</sup> is used for this, but I don't quite understand how to insert data into it correctly.
<sup>print(api.save_status_page(slug="google", data={'domainNameList': ["google.com"]}))</sup>
I get html code and 
<sup>requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html></sup>

**Comment by lucasheld** [comment]
Here is a full example.

First you need to add the monitors themselves.
Then add a status page and save it with the `publicGroupList` parameter. It consists of a `name` (the title of the monitor section inside the status page), a `weight` (to define the order if you have multiple monitor sections) and a `monitorList` (the ids of the monitors you want to add to this status page section).

```python
from uptime_kuma_api import UptimeKumaApi, MonitorType

username = "admin"
password = "secret123"

api = UptimeKumaApi("http://127.0.0.1:3001")
if api.need_setup():
    api.setup(username, password)
api.login(username, password)

monitor_id_1 = api.add_monitor(
    type=MonitorType.HTTP,
    url="http://127.0.0.1",
    name="monitor1"
)["monitorID"]

monitor_id_2 = api.add_monitor(
    type=MonitorType.HTTP,
    url="http://127.0.0.2",
    name="monitor2"
)["monitorID"]

slug = "statuspage1"
api.add_status_page(
    slug=slug,
    title="Status Page 1"
)
api.save_status_page(
    slug=slug,
    publicGroupList=[
        {
            'name': 'Services',
            'weight': 1,
            'monitorList': [
                {
                    "id": monitor_id_1
                },
                {
                    "id": monitor_id_2
                }
            ]
        }
    ]
)

api.disconnect()
```
